if(NOT DEFINED PEGIUM_COVERAGE_BINARY_DIR)
    message(FATAL_ERROR "PEGIUM_COVERAGE_BINARY_DIR must be set.")
endif()

file(GLOB_RECURSE PEGIUM_GCDA_FILES
    LIST_DIRECTORIES FALSE
    "${PEGIUM_COVERAGE_BINARY_DIR}/*.gcda"
)

if(PEGIUM_GCDA_FILES)
    file(REMOVE ${PEGIUM_GCDA_FILES})
endif()
