if(NOT DEFINED PEGIUM_SOURCE_DIR)
    message(FATAL_ERROR "PEGIUM_SOURCE_DIR must be set.")
endif()
if(NOT DEFINED PEGIUM_CONSUMER_SOURCE_DIR)
    message(FATAL_ERROR "PEGIUM_CONSUMER_SOURCE_DIR must be set.")
endif()
if(NOT DEFINED PEGIUM_CONSUMER_BINARY_DIR)
    message(FATAL_ERROR "PEGIUM_CONSUMER_BINARY_DIR must be set.")
endif()

file(REMOVE_RECURSE "${PEGIUM_CONSUMER_BINARY_DIR}")

set(PEGIUM_CONFIGURE_COMMAND
    "${CMAKE_COMMAND}"
    -S "${PEGIUM_CONSUMER_SOURCE_DIR}"
    -B "${PEGIUM_CONSUMER_BINARY_DIR}"
    "-DPEGIUM_SOURCE_DIR=${PEGIUM_SOURCE_DIR}"
)

if(DEFINED PEGIUM_CMAKE_GENERATOR AND NOT PEGIUM_CMAKE_GENERATOR STREQUAL "")
    list(APPEND PEGIUM_CONFIGURE_COMMAND -G "${PEGIUM_CMAKE_GENERATOR}")
endif()
if(DEFINED PEGIUM_CMAKE_GENERATOR_PLATFORM AND
   NOT PEGIUM_CMAKE_GENERATOR_PLATFORM STREQUAL "")
    list(APPEND PEGIUM_CONFIGURE_COMMAND -A "${PEGIUM_CMAKE_GENERATOR_PLATFORM}")
endif()
if(DEFINED PEGIUM_CMAKE_GENERATOR_TOOLSET AND
   NOT PEGIUM_CMAKE_GENERATOR_TOOLSET STREQUAL "")
    list(APPEND PEGIUM_CONFIGURE_COMMAND -T "${PEGIUM_CMAKE_GENERATOR_TOOLSET}")
endif()
if(DEFINED PEGIUM_CMAKE_MAKE_PROGRAM AND NOT PEGIUM_CMAKE_MAKE_PROGRAM STREQUAL "")
    list(APPEND PEGIUM_CONFIGURE_COMMAND
        "-DCMAKE_MAKE_PROGRAM=${PEGIUM_CMAKE_MAKE_PROGRAM}"
    )
endif()
if(DEFINED PEGIUM_CMAKE_C_COMPILER AND NOT PEGIUM_CMAKE_C_COMPILER STREQUAL "")
    list(APPEND PEGIUM_CONFIGURE_COMMAND
        "-DCMAKE_C_COMPILER=${PEGIUM_CMAKE_C_COMPILER}"
    )
endif()
if(DEFINED PEGIUM_CMAKE_CXX_COMPILER AND NOT PEGIUM_CMAKE_CXX_COMPILER STREQUAL "")
    list(APPEND PEGIUM_CONFIGURE_COMMAND
        "-DCMAKE_CXX_COMPILER=${PEGIUM_CMAKE_CXX_COMPILER}"
    )
endif()
if(DEFINED PEGIUM_CMAKE_BUILD_TYPE AND NOT PEGIUM_CMAKE_BUILD_TYPE STREQUAL "")
    list(APPEND PEGIUM_CONFIGURE_COMMAND
        "-DCMAKE_BUILD_TYPE=${PEGIUM_CMAKE_BUILD_TYPE}"
    )
endif()

execute_process(
    COMMAND ${PEGIUM_CONFIGURE_COMMAND}
    RESULT_VARIABLE PEGIUM_CONFIGURE_RESULT
)
if(NOT PEGIUM_CONFIGURE_RESULT EQUAL 0)
    message(FATAL_ERROR
        "Pegium FetchContent smoke configure failed with exit code "
        "${PEGIUM_CONFIGURE_RESULT}.")
endif()
